import { useGLTF } from "@react-three/drei";

const Coffee = (props) => {
  const { nodes, materials } = useGLTF("./coffee_machine.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 0.217, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sugar_container_StingrayPBS3_0.geometry}
            material={materials.StingrayPBS3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube1_StingrayPBS3_0.geometry}
            material={materials.StingrayPBS3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube2_StingrayPBS3_0.geometry}
            material={materials.StingrayPBS3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube7_StingrayPBS3_0.geometry}
            material={materials.StingrayPBS3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube6_StingrayPBS3_0.geometry}
            material={materials.StingrayPBS3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube5_StingrayPBS3_0.geometry}
            material={materials.StingrayPBS3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube4_StingrayPBS3_0.geometry}
            material={materials.StingrayPBS3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube3_StingrayPBS3_0.geometry}
            material={materials.StingrayPBS3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube_StingrayPBS3_0.geometry}
            material={materials.StingrayPBS3}
          />
        </group>
        <group position={[-2.928, 0.973, 0.936]} scale={0.956}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sugar_container_lambert6_0.geometry}
            material={materials.lambert6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube1_lambert6_0.geometry}
            material={materials.lambert6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube2_lambert6_0.geometry}
            material={materials.lambert6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube7_lambert6_0.geometry}
            material={materials.lambert6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube6_lambert6_0.geometry}
            material={materials.lambert6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube5_lambert6_0.geometry}
            material={materials.lambert6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube4_lambert6_0.geometry}
            material={materials.lambert6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube3_lambert6_0.geometry}
            material={materials.lambert6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SugarCube_lambert6_0.geometry}
            material={materials.lambert6}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffe_StingrayPBS2_0.geometry}
          material={materials.StingrayPBS2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plan_StingrayPBS4_0.geometry}
          material={materials.StingrayPBS4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffe_machine_StingrayPBS1_0.geometry}
          material={materials.StingrayPBS1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffe1_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface2_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface3_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface4_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface5_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface6_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface7_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface8_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface9_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface10_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface11_lambert6_0.geometry}
          material={materials.lambert6}
        />
      </group>
    </group>
  );
};

useGLTF.preload("./coffee_machine.glb");

export default Coffee;
